name = "spaghetto"

[dependencies]
aff = "*"
arrays = "*"
bifunctors = "*"
console = "*"
effect = "*"
either = "*"
foldable-traversable = "*"
foreign-object = "*"
functions = "*"
integers = "*"
maybe = "*"
node-buffer = "*"
node-fs-aff = "*"
node-path = "*"
ordered-collections = "*"
prelude = "*"
record = "*"
strings = "*"
transformers = "*"
tuples = "*"

[packages_db]
set = "https://raw.githubusercontent.com/purescript/registry-preview/main/package-sets/8.0.1.json"

[packages_db.extra_packages]
registry-lib = { git = "https://github.com/purescript/registry", ref = "master" }
